server:
  port: 1180
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/bz?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    connect-timeout: 5000
    ssl: false
  web:
    resources:
      static-locations: classpath:/static/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file-path: D:\\dev\\logs\\bz\\bz