server:
  port: 1180
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/bz?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl